version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: token_betting
      POSTGRES_PASSWORD: secure_password_here
      POSTGRES_DB: token_betting
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/admin-setup.sql:/docker-entrypoint-initdb.d/02-admin.sql
    networks:
      - betting_network

  # Backend API
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://token_betting:secure_password_here@postgres:5432/token_betting
      NODE_ENV: production
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - betting_network

  # Frontend Server (nginx)
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - betting_network

  # Admin Panel
  admin:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./admin:/usr/share/nginx/html
    networks:
      - betting_network

volumes:
  postgres_data:

networks:
  betting_network:
    driver: bridge
